# Registre de vérification des chiffres saisis dans les classeurs (vérifié en octobre 2026).
# Chaque entrée : clé (pour retrouver la ligne de paramètre), libellé, valeur affichée, type, comment c'est calculé,
# source, lien, statut, remarque. Types : « Chiffre publié », « Lu sur un graphique », « Calcul du site »,
# « Hypothèse du site », « Loi ou barème ». Statuts : « Confirmé », « Corrigé », « Confirmé (source secondaire) »,
# « Estimation, non vérifiable ».

PUB, GRAPH, CALC, HYP, LOI = "Chiffre publié", "Lu sur un graphique", "Calcul du site", "Hypothèse du site", "Loi ou barème"
OK, CORR, SEC, EST = "Confirmé", "Corrigé", "Confirmé (source secondaire)", "Estimation, non vérifiable"

U = {
    "sp_franchises": "https://www.service-public.gouv.fr/particuliers/actualites/A17166",
    "ps_tm": "https://www.publicsenat.fr/actualites/sante/consultations-medicales-la-ministre-de-la-sante-tempere-sur-la-hausse-du-ticket-moderateur",
    "jorf_0822": "https://www.legifrance.gouv.fr/jorf/jo/2026/08/22/0195",
    "rousset": "https://www.apmnews.com/documents/202510231649030.rapport_consolide_depassements_dhonoraires_VF_compressed.pdf",
    "l8624": "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042698839",
    "plfss26_a4": "https://www.assemblee-nationale.fr/dyn/contenu/visualisation/1088679/file/PLFSS2026-Annexe4-20251014-183718-59-11_avec%20couverture-2.pdf",
    "drees_usagers": "https://data.drees.solidarites-sante.gouv.fr/explore/dataset/depenses-de-sante-et-restes-a-charge/information/",
    "insee_emploi": "https://www.insee.fr/fr/statistiques/8376894",
    "insee_t6205": "https://www.insee.fr/fr/statistiques/8574681?sommaire=8574832",
    "ccss": "https://www.securite-sociale.fr/files/live/sites/SSFR/files/medias/CCSS/2026/CCSS%20mai%202026_assembl%C3%A9_V2.pdf",
    "csg_bareme": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2971",
    "cnav": "https://www.statistiques-recherche.lassuranceretraite.fr/app/uploads/2025/09/1.6-Les-prelevements-obligatoires-sur-les-retraites.pdf",
    "te371": "https://www.tresor.economie.gouv.fr/Articles/2025/09/25/analyse-de-la-composition-des-recettes-de-tva",
    "cor2026": "https://www.cor-retraites.fr/sites/default/files/2026-06/RA_2026_def.pdf",
    "cor2019": "https://www.cor-retraites.fr/sites/default/files/2019-11/Doc_2_%C3%A9tat_financement_0.pdf",
    "cae121": "https://cae-eco.fr/static/pdf/Focus_121_pension_2509123.pdf",
    "drees_eir": "https://data.drees.solidarites-sante.gouv.fr/explore/dataset/4178_distribution-des-pensions-mensuelles/information/",
    "drees_effectifs": "https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/effectifs-de-retraites-et-montants-des",
    "drees_panorama": "https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse-documents-de-reference/250731_PANORAMAS-retraites",
    "insee_epargne": "https://www.insee.fr/fr/statistiques/4764600",
    "insee_deces": "https://www.insee.fr/fr/statistiques/8719824",
    "insee_ndv": "https://www.insee.fr/fr/statistiques/2415628",
    "ipp_ch3": "https://www.ipp.eu/wp-content/uploads/2026/07/Chapitre_Desindexation_retraite___Rapport_Perspectives_Budgetaires_2027-4.pdf",
    "ipp129": "https://www.ipp.eu/publication/comment-mettre-a-contribution-les-retraites-pour-le-redressement-des-finances-publiques/",
    "igs": "https://www.jean-jaures.org/publication/face-a-la-grande-transmission-limpot-sur-les-grandes-successions/",
    "cgi777": "https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006069577",
    "cgi990i": "https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006069577",
    "insee_pib": "https://www.insee.fr/fr/statistiques/8996855",
    "vm2026": "https://www.assemblee-nationale.fr/dyn/contenu/visualisation/1087930/file/PLF%202026%20-%20V%26M%20TI%20-%20Evaluations%20des%20recettes.pdf",
    "insee_patrimoine": "https://www.insee.fr/fr/statistiques/8661938",
    "pfu2026": "https://placement.meilleurtaux.com/placement-financier/actualites/2026-avril/flat-tax-a-31-4-ce-qui-change-depuis-janvier-2026.html",
    "er1345": "https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse/250828_ER_depenses-de-sante",
    "cns": "https://data.drees.solidarites-sante.gouv.fr/explore/dataset/cns_financement/information/",
    "insee_menages": "https://www.insee.fr/fr/statistiques/3047266?sommaire=3138843",
    "insee_erfs2019": "https://www.insee.fr/fr/statistiques/5431993",
    "an161": "https://questions.assemblee-nationale.fr/q17/17-161QE.htm",
}

def E(cle, libelle, valeur, type_, calcul, source, url, statut=OK, note=""):
    return dict(cle=cle, libelle=libelle, valeur=valeur, type=type_, calcul=calcul, source=source, url=url, statut=statut, note=note)

RETRAITES = [
    E("emploi", "Personnes en emploi fin 2024", "30,4 millions", PUB, "Repris tel quel.", "Insee, Le marché du travail en 2024 (juin 2025)", U["insee_emploi"]),
    E("masse", "Salaires et traitements bruts 2024", "1 108,5 Md€", PUB, "Repris tel quel (total branches).", "Insee, comptes de la Nation 2024, tableau 6.205", U["insee_t6205"]),
    E("ratio", "Ratio salaire net / brut", "78 %", HYP, "Environ 22 % de cotisations et contributions salariales pour un salarié non cadre du privé ; arrondi.", "Hypothèse du site", "", EST),
    E("csgAct", "Taux de CSG sur les revenus d'activité", "9,2 %", LOI, "Taux légal.", "Code de la sécurité sociale, art. L136-8", U["csg_bareme"]),
    E("assiette", "Assiette de la CSG d'activité", "98,25 % du brut", LOI, "Abattement légal de 1,75 % pour frais professionnels.", "Code de la sécurité sociale, art. L136-1-1", ""),
    E("point", "Valeur d'un point de CSG d'activité", "12,0 Md€", CALC, "110,7 Md€ de CSG d'activité en 2025 ÷ 9,2 points.", "CCSS, rapport de mai 2026, tableau des recettes de CSG (110 670 M€ en 2025)", U["ccss"]),
    E("taux_reduit", "Taux de CSG des pensions (0 / 3,8 / 6,6 / 8,3 %) et seuils 2025 (12 817, 16 755, 26 004 € de RFR pour une part)", "barème", LOI, "Barème légal ; seuils confirmés par l'IPP (note n° 129, encadré 1).", "Code de la sécurité sociale, art. L136-8", U["csg_bareme"]),
    E("ass_normal", "Assiette des pensions au taux normal", "190,5 Md€", CALC, "Calée sur l'IPP : 1,5 Md€ net pour +0,9 point, l'impôt sur le revenu reprenant 12,5 % : 1,5 ÷ 0,875 ÷ 0,009.", "IPP, note n° 129 (2026), scénario C2", U["ipp129"]),
    E("ass_median", "Assiette des pensions au taux médian", "118,7 Md€", CALC, "Calée sur l'IPP : 4,2 Md€ net pour les taux médian et normal, soit 4,8 Md€ de CSG ; (4,8 − 1,71) ÷ 0,026.", "IPP, note n° 129 (2026), scénario C1", U["ipp129"]),
    E("ass_reduit", "Assiette des pensions au taux réduit", "27 Md€", CALC, "Complément pour retrouver les recettes de CSG sur les pensions (≈ 25,4 Md€ en 2025, 90 % des 28,3 Md€ de CSG sur les revenus de remplacement).", "CCSS, mai 2026", U["ccss"], EST),
    E("csgNet", "Rendement net d'une hausse de CSG des retraités", "87,5 %", CALC, "0,6 Md€ d'impôt sur le revenu perdu sur 4,8 Md€ de CSG (part déductible) : 1 − 0,6 ÷ 4,8.", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("rep_exonere", "Répartition des retraités par taux de CSG (exonéré 29 %, réduit 15 %, médian 27 %, normal 29 %)", "fin 2024", PUB, "Retraités du régime général au 31 décembre 2024.", "Cnav, recueil statistique, fiche 1.6", U["cnav"]),
    E("tvaNormal", "Rendement net d'un point de TVA, taux normal", "7,5 Md€", PUB, "Repris tel quel (net de la TVA payée par les administrations).", "DG Trésor, Trésor-Éco n° 371, tableau 2", U["te371"]),
    E("tvaTous", "Rendement net d'un point sur tous les taux", "11,4 Md€", PUB, "Repris tel quel.", "DG Trésor, Trésor-Éco n° 371, tableau 2", U["te371"]),
    E("ppa", "Perte de pouvoir d'achat par point de TVA, par cinquième de niveau de vie", "taux normal 0,39 % → 0,25 % ; tous taux 0,67 % → 0,42 %", GRAPH, "Valeurs lues sur le graphique 4 (mesure des barres, à 0,01 point près). Moyenne tous taux publiée : 0,5 %. Moyenne taux normal : 0,5 % × 0,312 ÷ 0,522 = 0,30 %.", "DG Trésor, Trésor-Éco n° 371, graphique 4", U["te371"], CORR, "Remplace l'ancienne valeur de 0,325 % (0,5 % × 8,9 ÷ 13,7, prorata du rendement brut), qui n'était pas lue sur le graphique."),
    E("partPensions", "Part des pensions dans le revenu des ménages retraités (avant impôts)", "77,8 %", CALC, "2 641 € de pensions ÷ (2 641 + 138 + 555 + 59) € de revenus, 2023.", "COR, rapport annuel juin 2026, figure 3.8 (Insee, ERFS 2023)", U["cor2026"]),
    E("partActivite", "Part des revenus d'activité dans le revenu des ménages actifs", "84,1 %", CALC, "4 245 € ÷ (4 245 + 213 + 383 + 209) €, 2023.", "COR, rapport annuel juin 2026, figure 3.8 et page 144", U["cor2026"]),
    E("pensionsTotales", "Masse des pensions 2025", "400 Md€", PUB, "361 Md€ de droit direct + 39 Md€ de droit dérivé.", "COR, rapport annuel juin 2026, chapitre 2", U["cor2026"]),
    E("depenses", "Dépenses de retraite 2025", "422,2 Md€", PUB, "Repris tel quel (14,1 % du PIB).", "COR, rapport annuel juin 2026", U["cor2026"]),
    E("pensionMoy", "Pension moyenne nette de droit direct", "1 541 €/mois", PUB, "Retraités résidant en France, fin 2023.", "Drees, Les retraités et les retraites, édition 2025", U["drees_panorama"]),
    E("ressources", "Ressources des retraites par nature (277,0 ; 49,3 ; 7,7 ; 21,9 ; 17,9 ; 17,4 ; 7,4 ; 11,2 ; 3,9 ; 1,3 ; 7,0 Md€)", "2025", PUB, "Repris du tableau ; 7,0 = 5,6 de produits financiers + 1,4 d'autres produits.", "COR, rapport annuel juin 2026, tableau 2.2", U["cor2026"]),
    E("etat_part", "État employeur : part « cotisation normale »", "21,0 Md€", CALC, "21,5 ÷ 50,4 Md€ (CAE, 2023) = 42,7 %, appliqués aux 49,3 Md€ de 2025 ; le reste (28,3) est le complément d'équilibre.", "CAE, Focus n° 121 (2025)", U["cae121"]),
    E("distribution", "Distribution des pensions totales brutes (46 tranches)", "fin 2020", PUB, "Tableau 5, colonne Ensemble, reprise à l'identique.", "Drees, EIR 2020, tableau 5", U["drees_eir"]),
    E("ret", "Retraités de droit direct fin 2024", "17,3 millions", PUB, "Repris tel quel (dont 16,4 en France).", "Drees, effectifs de retraités (mai 2026), cité par la presse ; site de la Drees indisponible lors de la vérification", U["drees_effectifs"], SEC),
    E("fac", "Passage des euros 2020 aux pensions 2027", "1,10", CALC, "Facteur choisi pour que la distribution redonne la médiane de l'IPP (1 639 €) et 35 % des retraités au-dessus de 2 000 €.", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("som", "Pension moyenne de la tranche « 4 500 € et plus » (€ 2020)", "6 000 €", HYP, "Choisie pour que la moyenne de la distribution (1 628 €) soit cohérente avec la pension moyenne totale de fin 2020.", "Hypothèse du site", "", EST),
    E("net", "Gain net pour les finances publiques / économie des régimes (gel)", "79 %", CALC, "5,2 Md€ nets ÷ 6,6 Md€ d'économie directe.", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("sortie", "Sortie annuelle des retraités actuels", "3 %", CALC, "≈ 570 000 décès de 60 ans ou plus (près de 9 sur 10 des 651 000 décès de 2025) ÷ 17,3 millions de retraités, arrondi.", "Insee, bilan démographique 2025", U["insee_deces"], EST),
    E("tp", "Taux plein ; trimestres requis", "50 % ; 172", LOI, "Régime général, générations nées à partir de 1965.", "Code de la sécurité sociale", ""),
    E("prel", "Prélèvements sur une pension au taux normal", "9,1 %", LOI, "CSG 8,3 % + CRDS 0,5 % + Casa 0,3 %.", "Code de la sécurité sociale", U["csg_bareme"]),
    E("epa", "Taux d'épargne des ménages de 70 ans ou plus", "21,8 %", PUB, "Repris tel quel (2017).", "Insee Première n° 1815 (2020)", U["insee_epargne"]),
    E("pb", "Part de base selon la pension (79 % jusqu'à 1 500 €, 63 % à partir de 3 000 €)", "profil", CALC, "Profil ajusté pour redonner les 4 chiffrages de l'IPP (6,6 ; 4,7 ; 3,6 ; 1,5 Md€ d'économie directe).", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("taux", "Revalorisation non versée par défaut", "2,5 %", PUB, "Revalorisation prévue au 1er janvier 2027 (inflation estimée pour 2026).", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("abattement", "Abattement de 10 % : plafond 4 439 € par foyer, plancher 454 € par pensionné", "revenus 2025", LOI, "CGI, art. 158, 5-a.", "IPP, note n° 129, encadré 1", U["ipp129"]),
    E("abat_points", "Recettes de l'abattement : 5,4 Md€ (suppression), 1,5 Md€ (plafond 2 545 €)", "2027", PUB, "Repris du tableau 1 ; entre ces points, interpolation linéaire du site.", "IPP, note n° 129, tableau 1", U["ipp129"]),
    E("ndv", "Niveaux de vie médians 1996-2024 (ensemble, retraités, personnes en emploi)", "€ 2024", PUB, "Repris de la figure 1 du fichier Insee ; en cas de rupture de série (2010, 2012, 2020), valeur après rupture.", "Insee, Niveau de vie selon le statut d'activité (ERFS), 2026 ; sources : Insee-DGFiP-Cnaf-Cnav-CCMSA, ERFS", U["insee_ndv"]),
    E("generations", "TRI, durée de retraite, espérance de vie à 60 ans, durée de carrière par génération", "1940-2000", PUB, "Repris des données des figures (scénario de référence), générations de 5 en 5.", "COR, rapport annuel juin 2026, figures 3.7, 3.6 et 3.2 (fichier de données)", U["cor2026"]),
    E("dec", "Décrochage annuel des pensions par rapport aux salaires", "1 %", HYP, "Pensions indexées sur les prix ; les salaires progressent en plus d'environ 1 % de productivité par an.", "Hypothèse du site", "", EST),
    E("ihc", "Part des ressources hors cotisations, 2004-2025", "≈ 18 % à 21,6 %", CALC, "ITAF + subventions d'équilibre + transferts externes (hors contribution d'équilibre de l'État employeur).", "COR, rapport annuel juin 2026, figure 2.11", U["cor2026"]),
    E("ihc1987", "Part des ressources hors cotisations en 1987", "12,1 %", CALC, "Lu sur la figure 2 du document : État (0,7 % du PIB), fiscalité (0,2 %) et transferts (0,3 %) rapportés aux ressources totales.", "COR, séance du 17 octobre 2019, document 2", U["cor2019"], EST),
    E("iq", "Part des ressources payée par les retraités : 0 en 1993, 5 % en 2018", "", PUB, "« Environ 5 % en 2018 » ; 0 avant l'affectation de la CSG aux retraites (1994).", "COR, séance du 17 octobre 2019, document 2", U["cor2019"]),
]

HERITAGE = [
    E("bareme_actuel", "Barème en ligne directe (5 % à 45 %, tranches de 8 072 à 1 805 677 €) et abattement de 100 000 €", "2024", LOI, "Barème légal, inchangé depuis 2011.", "CGI, art. 777 et 779", U["cgi777"], OK, "L'étude écrit « 15 392 € » pour la borne de la tranche à 15 % ; le bon chiffre, retenu ici, est 15 932 €."),
    E("av", "Assurance-vie : abattement de 152 500 € par bénéficiaire, 20 % jusqu'à 700 000 €, 31,25 % au-delà", "2024", LOI, "Primes versées avant 70 ans.", "CGI, art. 990 I", U["cgi990i"]),
    E("bareme_igs", "Barème de l'IGS (0 % jusqu'à 200 000 €, puis 5 / 15 / 25 / 35 / 45 / 50 %)", "", PUB, "Tableau 6 de l'étude (proposition du CAE, 2021).", "Fondation Jean-Jaurès (2024)", U["igs"]),
    E("pfu_indiv", "PFU sur les plus-values latentes (calcul individuel)", "30 %", LOI, "Taux de l'étude (2024) ; 31,4 % depuis 2026.", "Fondation Jean-Jaurès (2024)", U["igs"]),
    E("classeur", "Flux successoral, pilier 1, pilier 2 : formules et hypothèses du scénario « Étude 2024 »", "", PUB, "Repris du classeur de chiffrage de l'étude, cellule par cellule (vérifié : mêmes résultats à 0,01 Md€ près).", "Fondation Jean-Jaurès (2024), classeur « Chiffrage IGS »", U["igs"]),
    E("pib", "PIB 2025 (scénario actualisé)", "2 991,1 Md€", PUB, "2024 déduit : 2 991,1 ÷ 1,019 (croissance en valeur de 1,9 %).", "Insee, Les comptes de la Nation en 2025", U["insee_pib"]),
    E("dmtg", "Droits de succession et donations 2024-2026 (scénario actualisé)", "20,9 ; 20,7 ; 21,4 Md€", PUB, "Donations + successions : 4,9 + 16,0 ; 4,5 + 16,2 ; 4,4 + 17,0.", "Voies et moyens, PLF 2026, tome I", U["vm2026"]),
    E("patrimoine", "Patrimoine net des ménages (scénario actualisé)", "14 953 Md€ fin 2024", PUB, "2023 et 2022 déduits des évolutions publiées (+0,7 %, +0,6 %).", "Insee Première n° 2081", U["insee_patrimoine"]),
    E("pfu", "PFU (scénario actualisé)", "31,4 %", LOI, "12,8 % d'impôt + 18,6 % de prélèvements sociaux depuis le 1er janvier 2026.", "LFSS 2026", U["pfu2026"]),
    E("emploi", "Personnes en emploi ; salaires bruts ; ratio net / brut", "30,4 M ; 1 108,5 Md€ ; 78 %", PUB, "Voir le classeur Retraites (ratio : hypothèse du site).", "Insee", U["insee_emploi"]),
]

SANTE = [
    E("effort", "Taux d'effort pour la santé par niveau de vie, actifs et retraités", "2019", PUB, "Tableau complémentaire C, repris à l'identique.", "Drees, Études et Résultats n° 1345 (2025)", U["er1345"]),
    E("effortPrive", "Taux d'effort en primes et restes à charge par dixième et tops, composition des groupes", "2019", PUB, "Encadré 3 et tableaux complémentaires A et G, repris à l'identique.", "Drees, Études et Résultats n° 1345 (2025)", U["er1345"]),
    E("expo", "Part des retraités de chaque niveau de vie exposée aux taux normal et médian", "0 à 100 %", HYP, "Déduite des seuils de CSG : taux normal vers 2 400 € de pension brute pour une personne seule, taux médian vers 1 550 €.", "Hypothèse du site", "", EST),
    E("ass", "Assiettes des pensions aux taux normal et médian", "190,5 et 118,7 Md€", CALC, "Calées sur l'IPP (voir le classeur Retraites).", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("base", "Part de la pension venant des régimes de base", "67 %", CALC, "6,6 Md€ économisés par un gel de 2,5 % ÷ 0,025 = 264 Md€ de pensions de base, sur ≈ 400 Md€.", "IPP, note n° 129 et chapitre 3 (2026)", U["ipp129"]),
    E("def", "Solde de la branche maladie du régime général, 2026", "−13,8 Md€", PUB, "Repris tel quel.", "CCSS, rapport de mai 2026", U["ccss"]),
    E("cotC", "Cotisation maladie sur les retraites complémentaires", "1 %", LOI, "Retraités au taux médian ou normal de CSG.", "Question écrite n° 161 (2024) ; service-public.gouv.fr", U["an161"]),
    E("menages", "Ménages dans le champ de l'enquête", "28,8 millions", CALC, "63,4 millions de personnes ÷ 2,2 personnes par ménage.", "Insee Première n° 1875 ; Insee, ménages", U["insee_erfs2019"]),
    E("evol", "Évolution 2019 → 2024 des dépenses payées par les complémentaires et les ménages", "× 1,186", CALC, "(32,52 + 19,96) ÷ (26,74 + 17,52) Md€.", "Drees, comptes de la santé (données en ligne)", U["cns"]),
    E("partP", "Part des pensions dans le revenu des retraités ; répartition par taux de CSG", "77,8 % ; 29 / 27 %", CALC, "Voir le classeur Retraites.", "COR 2026, figure 3.8 ; Cnav", U["cor2026"]),
]

SANTE += [
    E("franchises", "Franchises (1 € par boîte et acte paramédical, 4 € par transport) et participations (2 €) ; plafonds annuels", "70 € + 70 € depuis le 1er octobre 2026", LOI, "Plafonds relevés de 50 € à 70 € chacun ; montants unitaires inchangés.", "Décret n° 2026-858 du 11 septembre 2026 (service-public.gouv.fr)", U["sp_franchises"]),
    E("fr_ctrl1", "Doublement des franchises, participations et plafonds (PLFSS 2026, abandonné)", "2,3 Md€", PUB, "Point de contrôle du modèle (retrouvé à 5 % près).", "CCSS, mai 2026, fiche 2.2", U["ccss"]),
    E("fr_ctrl2", "Doublement des seuls plafonds (100 € + 100 €)", "≈ 0,75 Md€", PUB, "Point de contrôle du modèle ; chiffre annoncé par le gouvernement en juillet 2026.", "Public Sénat, Caducée (juillet-septembre 2026)", "", SEC, "Le rendement du décret finalement pris (70 € + 70 €) n'a pas été publié."),
    E("fr_obs", "Franchises et participations payées par personne et par âge", "0 à 52 € (2023)", PUB, "Repris tel quel ; sert à caler le modèle par âge.", "Drees, dépenses de santé et restes à charge 2023", U["drees_usagers"]),
    E("sigma", "Dispersion du modèle de franchises (log-normale)", "1,4", HYP, "Choisie pour retrouver les deux points de contrôle officiels.", "Hypothèse du site", "", EST),
    E("tm", "Ticket modérateur des consultations : rendement d'un point", "0,11 Md€", CALC, "1,1 Md€ transférés aux complémentaires pour 30 → 40 % (PLFSS 2025) ÷ 10.", "PLFSS 2025, mesure citée par Public Sénat et Previssima", U["ps_tm"], SEC),
    E("tm2027", "Hausses du ticket modérateur de 2027 (dentaire, dispositifs, médicaments, transports)", "≈ 1,5 Md€", PUB, "Décrets publiés au JO du 22 août 2026 ; montant tiré de la presse spécialisée. Non compté (déjà décidé).", "Décrets n° 2026-809 à 812", U["jorf_0822"], SEC),
    E("ald", "ALD : cures thermales alignées (0,2 Md€), fin des ALD « non exonérantes » (0,1 Md€)", "0,3 Md€", PUB, "Mesures du PLFSS 2026 abandonnées en LFSS.", "CCSS, mai 2026, fiche 2.2", U["ccss"]),
    E("dep", "Dépassements d'honoraires 2024 ; part remboursée par les complémentaires", "4,5 Md€ ; 37 à 40 %", PUB, "Repris tel quel (milieu retenu : 38,5 %).", "Mission Rousset-Monnet (octobre 2025)", U["rousset"]),
    E("sansOc", "Part de la population sans complémentaire santé", "5 %", PUB, "Repris tel quel.", "Mission Rousset-Monnet (octobre 2025)", U["rousset"]),
    E("tsa", "Taxe de solidarité additionnelle : taux ; recettes 2025", "13,27 % ; 6,558 Md€", LOI, "Valeur d'un point : 6,558 ÷ 13,27 ≈ 0,49 Md€ (un peu forte : certains contrats sont taxés à 20,27 %).", "CSS, art. L862-4 ; CCSS, mai 2026", U["l8624"]),
    E("entreprise", "Contrats santé et prévoyance d'entreprise : assiette exemptée ; manque à gagner net ; forfait social", "24,3 Md€ ; 5,6 Md€ ; 8 %", PUB, "Prévision 2026, tableau 9 (santé et prévoyance ensemble).", "PLFSS 2026, annexe 4", U["plfss26_a4"]),
    E("primesAge", "Prime mensuelle de complémentaire à 20 et 85 ans", "36 € ; 142 €", PUB, "Interpolée linéairement entre ces âges pour répartir une hausse de primes.", "Drees, organismes complémentaires (2025)", "https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/250923_DATA_organismes-couvertures-compl%C3%A9mentaires-sant%C3%A9"),
]

BILAN = [
    E("tva_point", "Rendement d'un point de TVA au taux normal (net)", "7,5 Md€", PUB, "Repris tel quel.", "DG Trésor, Trésor-Éco n° 371", U["te371"]),
    E("perte_tva", "Perte de pouvoir d'achat moyenne pour 1 point de TVA au taux normal", "0,30 %", GRAPH, "Graphique 4 (voir le classeur Retraites).", "DG Trésor, Trésor-Éco n° 371", U["te371"]),
    E("valeur_point", "Valeur d'un point de CSG sur les revenus d'activité", "12,0 Md€", CALC, "110,7 Md€ ÷ 9,2.", "CCSS, mai 2026", U["ccss"]),
    E("effet_net", "Part de la CSG gardée après impôt sur le revenu", "87,5 %", CALC, "Rendement net ÷ brut des chiffrages de l'IPP ; appliqué en miroir à une baisse de CSG des actifs.", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("pensions", "Masse des pensions", "400 Md€", PUB, "Arrondi.", "COR, rapport annuel 2026", U["cor2026"]),
    E("ass", "Assiettes des pensions aux taux normal et médian", "190,5 et 118,7 Md€", CALC, "Calées sur l'IPP (voir le classeur Retraites).", "IPP, note n° 129 (2026)", U["ipp129"]),
    E("revalo", "Revalorisation des pensions après une hausse de TVA", "perte moyenne × masse des pensions", HYP, "Minimum : l'indice des prix monte un peu plus que la perte moyenne de pouvoir d'achat.", "Hypothèse du site", "", EST),
]

